import logo from './logo.svg';
import './App.css';
import axios from "axios";
import React from "react";

function App() {
  let urlstr = `https://newhaven.io
  #mid-atlantic
  http://www.dctechslack.com
  http://slack.borojs.com/
  http://www.nyctechslack.com/
  http://www.nycdevs.org
  https://launchpass.com/nycdevops
  http://baltimoretech-slack.herokuapp.com/
  https://www.sendgrowth.com/psl/
  https://phillydev.org/
  https://codeforphilly.org/register
  https://docs.google.com/forms/d/e/1FAIpQLScaAROJx4kZQ7cPhATWWhfmpHK3YP6ourLgPalPwRqIMI1bmg/viewform?c=0&w=1
  https://nepatech.slack.com/
  https://wbpc-meetup.slack.com/
  https://codeandsupply.co/chat
  /thisdot/tech-community-slacks/blob/master/amishtech.slack.com
  #the-midwest
  http://www.cialug.org/
  https://cialug.slack.com/
  http://dsmwebcollective.com
  https://dsmwebcollective.herokuapp.com/
  http://www.dsmwebgeeks.com/
  https://dsmwebgeeks.slack.com/
  https://secdsm.org/
  https://secdsm.slack.com/
  http://www.startupiowachat.com/
  http://wpdsm.org/
  http://wordpressdsm.herokuapp.com/
  http://www.chicagotechslack.com/
  http://slack.chicagoaws.com/
  https://www.chipy.org/
  https://joinchipyslack.herokuapp.com/
  /thisdot/tech-community-slacks/blob/master/chitechdiversity.slack.com
  http://indyhackers-slack.herokuapp.com/
  https://devict-slackin.herokuapp.com/
  http://louisville.io
  http://louisville.slack.com
  http://startuplansing.org/join-slack/
  https://tinyurl.com/Join-DSIT-Slack
  http://www.msptech.online/
  http://twincities-chaosengr.slack.com
  https://kctechgroup.org/
  https://kcwomenintech.org/
  https://seckc.org/
  https://seckc.slack.com/
  http://sgfwebdevs.com/
  https://sgfwebdevs.slack.com/
  https://stltech.org
  https://techlife-columbus-slack.herokuapp.com/
  https://cleveland-tech.herokuapp.com/
  https://cincytech.slack.com
  https://mke-slack.herokuapp.com/
  http://newslack.appletonmakerspace.org
  #the-southeast
  http://magiccitytech.org/
  https://tech256.com/
  https://nwa-devs-slackgroup.herokuapp.com/
  https://lrdev.typeform.com/to/aZ9Hr8?fbclid=IwAR3PhhP5XQZzcFmYo2DDfDo_CeQgA9SXCrZmZnl2_ERaWo5uIqV0wM7Ixro
  http://swflcoders.slack.com/
  https://gnvconnect.com/
  http://jacksonville-tech.com/
  http://fedm.herokuapp.com/
  https://wyn.tech/
  https://orlandodevs.com/slack
  https://suncoast-devs.slack.com/
  http://tampabaytech.org/slack/
  https://tampadevs.com
  https://techsav.co/
  http://tech404.io/
  https://athdev.org
  https://www.bluegrassdevs.org/
  https://www.startuplexington.org/
  http://slackin.louisville.io/
  https://slack.charlottedevs.com/
  https://triangle-devs-slack-inviter.herokuapp.com/
  https://charlestontechslack.herokuapp.com/
  https://chadev.com
  https://www.devanooga.com/slack/
  http://knoxdevs-slackin.herokuapp.com/
  http://slack.memphistechnology.org/
  https://www.meetup.com/BoroDev/
  http://nashdev.com/
  https://www.meetup.com/TriDev/
  https://nrvdev.slack.org
  https://cville.slack.com
  https://rocktowntech.slack.com
  #the-southwest
  https://azwebdevs.org/signin
  http://techcommunityofnm.org/
  http://slack.techlahoma.org/
  https://weirdswiftslack.mybluemix.net/
  http://slack.refreshaustin.org/
  https://codementorship.slack.com
  https://slack.open-austin.org/
  https://sanantoniodevs.com
  #the-west
  https://join-jsla-slack.herokuapp.com/
  https://lascalausers.slack.com/
  https://sbtechcoop.slack.com/
  https://sac-tech.herokuapp.com/
  https://denverdevs.org/
  https://www.gettechfriends.com/
  http://fcip.slack.com/
  https://coloradospringsdevs.herokuapp.com/
  http://madeinloveland.slack.com/
  http://co-freelance-webdevs.slack.com/
  https://angularcolorado.com/
  https://hawaiislack.com/
  https://infiniteredcommunity.herokuapp.com/
  http://nodepdx.slack.com/
  https://portlandreactjs.herokuapp.com/
  https://pdx-startups-slack.herokuapp.com/
  https://bit.ly/wwcpdx-slack
  https://qautah.slack.com/
  https://slack.utahjs.com/
  http://urug.herokuapp.com/
  https://angular-seattle.slack.com
  https://openseattle.slack.com
  https://seattledesigners.slack.com
  https://seattlerbslack.herokuapp.com/
  https://seattlejshackers.slack.com
  https://techseattle.slack.com/messages/C045K4QLR/
  https://seattlecodecrafters.slack.com
  #other-countries
  #-argentina
  https://slack.meetupjs.com.ar/
  https://freecodecampba.org/chat/
  https://pro-gramadores.org/
  #-australia
  https://devanz.slack.com
  https://brisbane-developers.slack.com
  #-brazil
  https://iosdevbr.herokuapp.com/
  http://slack.androiddevbr.org/
  http://braziljs-slack.herokuapp.com/
  http://ctgroups.slack.com/
  https://iosdevbr.herokuapp.com/
  http://slack.androiddevbr.org/
  https://flutterbr.herokuapp.com/
  https://react-brasil-slack.herokuapp.com/
  http://gdgbrazil.herokuapp.com/
  #-cote-divoire-ivory-coast
  http://slack.codedivoire.com/
  #-canada
  https://devedmonton.com/
  https://yvrdev.herokuapp.com/
  https://yyj-tech.ca/
  http://yyjtechladies.com/
  https://ottawastartups.slack.com/messages/C0408SPU4/
  http://startup6ix.com/
  http://slack.torontojs.com/
  http://yowdev-slackin.herokuapp.com/
  http://codepen-ott.herokuapp.com/
  http://sketchmtl.now.sh/
  https://witmgroup-slack.herokuapp.com/
  https://www.halihax.com/
  #-chile
  https://devschile.cl/
  http://bit.ly/AngularChileSlack
  https://noders.com/
  https://pro-gramadores.org/
  #-denmark
  https://slack.devdk.org/
  https://www.womenintech.dk/
  #-finland
  https://www.angular.fi/
  https://koodiklinikka.fi/
  https://turkufrontend.fi
  https://turkulovesfrontend.herokuapp.com/
  #-france
  https://slack-francejs.now.sh/
  https://android-dev-france.slack.com/
  https://communityinviter.com/apps/swift-baguette/inviteme/
  https://lesagilistes.slack.com
  https://frontendfr.slack.com
  https://geekdpt.io
  http://elsass-dev.fr
  https://github.com/xtuc
  https://rennesjs.slack.com/
  http://rennesjs.org/
  https://lyonjs.slack.com/
  https://twitter.com/Paul_Mougel
  https://slack.lyontechhub.org/
  https://slack.nantes.community/
  /thisdot/tech-community-slacks/blob/master/comm-montpellier.slack.com
  https://comm-montpellier-invit.herokuapp.com/
  https://join.slack.com/t/nantesjs/shared_invite/enQtMjU0NTcxMzU4MDM2LTMwMjljNjEzMmViYzllOGY5Y2VlMjI4MzMxM2QzZDYwZWRhMDA0YWFjMDgwZDI4NjFhN2Y4NDU4NjMwOWUwOTc
  https://productpeoplenantes.slack.com
  #-germany
  https://workshops-de.slack.com
  https://workshops-de.slack.com/join/shared_invite/enQtMzIyMjk5MzE3MTA5LWMxMzViMzFjNmIzY2U4NDU5YjY1NzY0YmU3ZDZkMDY2YTc2OGJlMTc1MzUwYTMwYzkxMTZiMWFjNWZlYzVjMWU
  https://reactjs.de
  https://reactjs-de.slack.com/
  https://join.slack.com/t/reactjs-de/shared_invite/enQtNDAwNjEzNTc2MTE0LTdiZGFjZmNmYWE0ZWZmMmUzOGI3YTA1ZDg2NTk1N2UwZmE3YjJkNDgxNjk4Mzg1Zjg3YzNhZjNhYTgxMGE2OTQ
  https://jina.ai/
  https://slack.jina.ai/
  #-ghana
  https://devcongress-community.slack.com
  http://slack.devcongress.org/
  #-india
  https://friends.hasgeek.com/
  https://hasgeek.com/
  http://gdg-pune.slack.com/
  https://gdgahmedabad.slack.com/
  https://gdggandhinagar.slack.com/
  http://gdgbaroda-invite.herokuapp.com
  https://mindorks.com/join-community/
  https://reactbangalore.herokuapp.com/
  http://reactnativebangalore.nativebase.io/
  http://gdgbangalore-slack-invite.herokuapp.com/
  https://blrdroid-slack.herokuapp.com/
  http://slack.openebs.io/
  https://gdgndslackinvite.herokuapp.com/
  http://connect.gdgcbe.com/
  https://swiftindia.in/community/
  #-indonesia
  https://perkodi.org/
  https://ruby.id/
  http://ruby.id/slack
  #-ireland
  https://slackin-itc.herokuapp.com/
  http://irishtechcommunity.com/channels/
  #-israel
  http://israeltech.slack.com
  #-italy
  http://beam-italia.herokuapp.com/
  https://slackin-codingjam.herokuapp.com
  http://codingjam.it/
  http://slack.devday.it
  https://devday.it
  https://slack.developers.italia.it
  https://italiajs.herokuapp.com/
  https://romajs.herokuapp.com/
  http://slack.scala-italy.it/
  http://codegardenroma.herokuapp.com/
  http://rust-italia.herokuapp.com/
  https://slack-grusp.herokuapp.com/
  https://milanofrontend.herokuapp.com/
  http://laravel-italia.it/articoli/laravel-italia-e-su-slack
  https://it.wordpress.org/slack/
  https://aws-community-italy.slack.com/
  #-japan
  https://devjapan.slack.com/
  https://hackernewstokyo.slack.com
  https://tokyodev-round-tables.slack.com
  #-malaysia
  https://gdgmy-slack.herokuapp.com/
  https://www.gdgkl.org/
  http://www.gdggeorgetown.com/
  http://gdgkk.info/
  #-mexico
  https://slack.devz.mx/
  http://codersmexico.com.mx/
  #-new-zealand
  https://javascript.org.nz/slack
  https://developnz.herokuapp.com
  #-nigeria
  https://twitter.com/ngnigeria
  https://consonance-invite.herokuapp.com/
  https://devcenter-square-slack.herokuapp.com
  https://frontstack.io/
  https://ionic-nigeria.herokuapp.com/
  https://www.laravelnigeria.com/
  https://slack.paystack.com/
  https://py-slack-invite.herokuapp.com
  https://www.meetup.com/lagosscala/
  https://bit.ly/scaslacksignup
  https://wecode.ng/
  #-philippines
  http://www.phackers.com/
  #-poland
  https://jvm-poland.slack.com
  https://slack.callstack.io
  #-romania
  https://timjs.slack.com
  https://jsheroes-community.slack.com
  #-south-africa
  https://zatech.co.za/
  #-serbia
  http://slack.jsbelgrade.org/
  #-uk
  http://frontendlondon-slack.herokuapp.com/
  http://mcrtech-slack.herokuapp.com/
  https://leicesterjs.org/slack
  https://www.leedsdevs.co.uk
  #-uruguay
  /thisdot/tech-community-slacks/blob/master/owu.slack.com
  #-ukraine
  http://slack.ukrops.club/
  #-vietnam
  http://chat.ruby.org.vn/
  #conferences-public-slack-communities
  https://conference.ctocraft.com
  http://mobileera.herokuapp.com/
  http://ngvikings.herokuapp.com/
  https://communityinviter.com/apps/cloud-native/cncf
  #bonus-channels
  #general-tech-slack-communities
  #frameworks
  https://slackin.angularbeers.org/
  https://angularchat.co/
  https://slack.babeljs.io/
  https://ember-community-slackin.herokuapp.com/
  http://slack.feathersjs.com/
  https://hashtagnodejs.slack.com/messages/C066268AG/
  https://ionicworldwide.herokuapp.com/
  https://larachat.co/
  https://laravelbrasil.slack.com/
  https://jina.ai/
  https://nativescriptcommunity.slack.com/
  https://developer.telerik.com/wp-login.php?action=slack-invitation
  http://slack.nativebase.io/
  https://www.reactiflux.com/
  https://slack.reactjsnews.com/
  http://www.vueslack.com/
  https://chat.vuejs.org/
  https://vuejs-brasil.herokuapp.com/
  https://wordpress.slack.com/
  https://make.wordpress.org/chat/
  https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877
  https://www.ampproject.org/
  #languages
  https://beerjs-slack-invite.herokuapp.com/
  http://clojurians.net/
  https://elixir-slackin.herokuapp.com/
  https://erlang-slack.herokuapp.com/
  https://gophersinvite.herokuapp.com/
  https://javadevbr.herokuapp.com/
  https://php.ug/slackinvite
  http://pythondevelopers.herokuapp.com/
  https://pythondev.slack.com
  https://rubydevs.herokuapp.com/
  http://www.rubyonrails.link/
  http://slack.strapi.io/
  https://wealljs.org
  http://javascript-devs.herokuapp.com/
  http://slack.kotlinlang.org/
  https://gitter.im/nim-lang/Nim
  https://t.me/NimArgentina
  #design
  https://designtalks.slack.com/
  https://www.designerhangout.co/
  http://slack.uxmastery.com/
  #security
  https://nodejs-security-wg.herokuapp.com
  #technologies
  https://chromiumdev-slack.herokuapp.com/
  https://www.getdbt.com/
  https://firebase-community.appspot.com/
  http://slack.k8s.io/
  https://community-slack.mongodb.com/
  https://node-js.slack.com/messages/C3910A78T/
  https://polymer-slack.herokuapp.com/
  https://postgres-slack.herokuapp.com/
  https://slackin-socketio.now.sh/
  https://firebase.community/
  https://holodevelopersslack.azurewebsites.net/
  #general-dev
  https://codebuddiesmeet.herokuapp.com
  http://bit.ly/CodeNewbieSlack
  https://codingblocks.slack.com/
  https://devchat.devolio.net/
  https://devopschat.slack.com/
  https://deviofoundation.slack.com/
  https://europeandevexplorer.typeform.com/to/MC3qnG
  https://functionalprogramming.slack.com
  http://www.hashtagdevelopers.com/
  http://msdev.chat/
  http://modernagile.slack.com/
  https://frontenddevelopers.slack.com
  http://frontenddevelopers.org/
  https://mr-frontend-slack-invite.herokuapp.com/
  https://techmasters.chat/
  https://codebuddies.org/slack
  https://developerarmy.slack.com/
  #general-testing--qa
  https://oneofthethree.slack.com/
  http://moderntesting.org
  https://www.ministryoftesting.com/slack_invite
  https://testersio.slack.com
  #intro-to-dev--learning
  https://www.jrdevjobs.com/slack
  https://learncoding.slack.com/messages/C04G48BKC/
  http://slack.themeteorchef.com/
  #women
  http://witchat.github.io/
  https://ladiesofwp.slack.com
  https://vuevixens.slack.com
  #misc-interest
  https://web-a11y.herokuapp.com/
  https://devopschat.co/
  http://slack.js-data.io/
  https://operationcode.org
  https://writethedocs.slack.com/join/shared_invite/zt-tfokbfyb-4Yxwk8oTZGAQDHmITJGQyQ#/shared-invite/email
  #community-groups
  http://fedsonslack.com/
  https://join.slashrocket.io/
  https://triangle-devs-slack-inviter.herokuapp.com
  http://rteendeveloperslack.herokuapp.com/
  https://discordapp.com/invite/reasonml
  https://getgrav.org/slack
  https://pyrocms.com/slack
  http://evangelistcollective.github.io
  https://damp-lake-50659.herokuapp.com/
  https://sitecorechat.slack.com
  https://ios-developers.slack.com
  https://android-united.slack.com
  https://comm.chat
  /thisdot/tech-community-slacks/blob/master/theleaddeveloper.slack.com
  https://ctocraft.com
  #blogging
  https://programmingbloggers.herokuapp.com/
  #resources
  https://scotch-slack.herokuapp.com/
  https://spec.fm/slack
  https://karangoel.typeform.com/to/mEl3P9
  /topics/community
  #readme
  /thisdot/tech-community-slacks/blob/master/CODE_OF_CONDUCT.md
  /thisdot/tech-community-slacks/stargazers
  /thisdot/tech-community-slacks/watchers
  /thisdot/tech-community-slacks/network/members
  /thisdot/tech-community-slacks/releases
  /orgs/thisdot/packages?repo_name=tech-community-slacks
  /thisdot/tech-community-slacks/graphs/contributors
  https://github.com/ladyleet
  https://github.com/SofiEstevez
  https://github.com/tyrelchambers
  https://github.com/necoline
  https://github.com/warissara
  https://github.com/johnsonsirv
  https://github.com/dhanush13-c
  https://github.com/dustyjuhl
  https://github.com/lirantal
  https://github.com/karlhorky
  https://github.com/ryanmaynard
  /thisdot/tech-community-slacks/graphs/contributors
  https://github.com
  https://docs.github.com/en/github/site-policy/github-terms-of-service
  https://docs.github.com/en/github/site-policy/github-privacy-statement
  https://github.com/security
  https://www.githubstatus.com/
  https://docs.github.com
  https://support.github.com?tags=dotcom-footer
  https://github.com/pricing
  https://docs.github.com
  https://services.github.com
  https://github.blog
  https://github.com/about`
  React.useEffect(() => {
    async function fetchData(){
      let urls = urlstr.split("\n");
      let successUrls = []
      for(let i = 0;i < urls.length;i++){
        try{
          let r = await axios.get(urls[i])
          //console.log(r)
          successUrls = [...successUrls,urls[i]]
          if(r.status == 200){
            console.log(urls[i])
          }
        }catch(e){
         // console.log(e)
        }
      }
      
    }
    fetchData();
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
